version: '3'

services:
  # ~ ~ ~ ~ ~
  # POSTGRES
  # ~ ~ ~ ~ ~
  postgres-service:
    hostname: postgres-service
    restart: on-failure
    image: postgres
    environment:
      - POSTGRES_USER=ZbPDqDa
      - POSTGRES_PASSWORD=mKPegDYBFpsqbWlq
      - POSTGRES_DB=qtbsxAIUe

  backend:
    build: .
    command: ["/bin/wait-for-it.sh", "postgres-service:5432", "--", "/bin/start-gunicorn.sh"]
    environment:
      - POSTGRES_USER=ZbPDqDa
      - POSTGRES_PASSWORD=mKPegDYBFpsqbWlq
      - POSTGRES_DB=qtbsxAIUe
      - DOCKER=true
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - postgres-service